Добавляет сетки страниц на flex
htmlacademy-htmlcss/2188619-device-35 pull request #11
Opened 2022-10-22 12:05 UTC by Aleksey177

Попытался выровнять по горизонту но понял что на гридах проще и не стал ровнять до конца.

2022-10-23 17:41 UTC, Kartaviy-arteom requested changes

2022-10-23 17:41 UTC, Kartaviy-arteom commented on index.html
> +      <div class="mailing-container">
этот тег не закрыт

2022-10-23 17:41 UTC, Kartaviy-arteom commented on index.html
> +          <section class="mailing-form-input">
секции нужен заголовок

2022-10-23 17:41 UTC, Kartaviy-arteom commented on catalog.html
> +        <div class="breadcrumbs-container">
тег не закрыт

2022-10-23 17:41 UTC, Kartaviy-arteom commented on catalog.html
> +                  <button class="sorting-button-down" type=button aria-label="Сортировка по цене от большего ">
тут ошибка с закрытием кнопки

2022-10-23 17:41 UTC, Kartaviy-arteom commented on catalog.html
> +          <section class="footer-phone-contacts">
заголовок для секции

2022-10-23 17:41 UTC, Kartaviy-arteom commented on styles/styles.css
> +  margin: 30px 0 0 60px;
по хедеру пересмотреть отступ, контейнер, выравнивание элементов. и ограничение высоты в хедере не нужна

2022-10-23 17:41 UTC, Kartaviy-arteom commented on styles/styles.css
>  .navigation-search {
тут получается двойная рамка

2022-10-23 17:41 UTC, Kartaviy-arteom commented on index.html
> +        <section class="services">
тут нужно растянуть фон

2022-10-23 17:41 UTC, Kartaviy-arteom commented on styles/styles.css
> +.index-elivery-container {
верхний элемент толкает последующий
кнопка это весь элемент

2022-10-23 17:41 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding: 65px;
зачем тут такие паддинги?

2022-10-26 09:48 UTC, Aleksey177 commented on index.html
> +      <div class="mailing-container">
Закрыл тег

2022-10-26 09:51 UTC, Aleksey177 commented on index.html
> +          <section class="mailing-form-input">
Добавил заголовок H3

2022-10-26 09:52 UTC, Aleksey177 commented on catalog.html
> +        <div class="breadcrumbs-container">
Закрыл тег

2022-10-26 09:54 UTC, Aleksey177 commented on catalog.html
> +                  <button class="sorting-button-down" type=button aria-label="Сортировка по цене от большего ">
Исправил, стрелки добавил чтобы видеть кнопки, потом поменяю.

2022-10-26 09:58 UTC, Aleksey177 commented on catalog.html
> +          <section class="footer-phone-contacts">
Добавил заголовок

2022-10-26 11:00 UTC, Aleksey177 commented on styles/styles.css
> +  margin: 30px 0 0 60px;
Убрал ограничение по высоте, пересмотрел отступы,.

2022-10-26 11:16 UTC, Aleksey177 commented on index.html
> +        <section class="services">
Фон растянут, изменил отступы.

2022-10-26 11:31 UTC, Aleksey177 commented on styles/styles.css
> +  padding: 65px;
Заменил на марджины

2022-10-26 19:47 UTC, Kartaviy-arteom approved these changes
Нужно при следующих задания поправить валидность и придерживаться системы отступов, это упростит переиспользование

2022-10-26 19:47 UTC, Kartaviy-arteom commented on styles/styles.css
> +  height: 300px;
тебе не стоит ограничивать так высоту, пусть она зависит от контента. Чтобы он не схлопнулся если контента нет, можно использовать min-height

2022-10-26 19:48 UTC, merged