Сетки компонентов на флексах
htmlacademy-htmlcss/2188619-device-35 pull request #12
Opened 2022-11-03 16:39 UTC by Aleksey177

2022-11-05 08:49 UTC, Kartaviy-arteom requested changes

2022-11-05 08:49 UTC, Kartaviy-arteom commented on styles/styles.css
>  .services-container {
тебе не нужно, чтобы контент выпадал из контейнера. Для фона можно использовать градиент

2022-11-05 08:49 UTC, Kartaviy-arteom commented on styles/styles.css
> +  min-height: 253px;
justify-content: flex-start;
flex-wrap-wrap
элементам правый margin и скидывать каждому 6 или родителю flex-gap

2022-11-05 08:49 UTC, Kartaviy-arteom commented on styles/styles.css
> +  margin-left: 45px;
ей не нужен margin. нужно выровнять navigation-divice-item
divice - будет ошибка в наименовании, device

2022-11-05 08:49 UTC, Kartaviy-arteom commented on styles/styles.css
> +  margin-top: -20px;
ссылка значительно больше логотипа, так не должно быть

2022-11-05 08:49 UTC, Kartaviy-arteom commented on styles/styles.css
>  .product-card {
тут не нужен такой верхний и левый падинг. Карточка это серая картинка и подпись снизу. Вокруг карточки белый фон, это падинги списка. То что у тебя сейчас ссылка - это и есть вся карточка. Выравнивание внутри списка - это margin, gap и тд. product-card-image -снизу margin. Можно использовать это https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

2022-11-05 08:49 UTC, Kartaviy-arteom commented on styles/styles.css
>  .pagination-link {
не удачный способ выравнивания, если нужно изменить размер шрифта, придется менять паддинг.
Попробуй например так: display:grid, place-content: center

2022-11-05 08:49 UTC, Kartaviy-arteom commented on catalog.html
> +                        height="380" alt="Селфи-палка «Следуй за мной».">Селфи-палка «Следуй<br> за мной»
button-show-more - нужно выровнять ее по центру по-другому

2022-11-05 13:37 UTC, Aleksey177 commented on styles/styles.css
>  .services-container {
Заменил на градиент

2022-11-05 13:48 UTC, Aleksey177 commented on styles/styles.css
> +  min-height: 253px;
Сделал отступы слева и обнулил у каждого 6-го

2022-11-05 14:19 UTC, Aleksey177 commented on styles/styles.css
> +  margin-left: 45px;
Device исправил.  Выровнил navigation-device-item

2022-11-05 14:27 UTC, Aleksey177 commented on styles/styles.css
> +  margin-top: -20px;
Уменьшил до размера логотипа

2022-11-05 14:59 UTC, Aleksey177 commented on styles/styles.css
>  .pagination-link {
Сделал

2022-11-06 14:08 UTC, Aleksey177 commented on styles/styles.css
>  .product-card {
Исправил

2022-11-06 14:08 UTC, Aleksey177 commented on catalog.html
> +                        height="380" alt="Селфи-палка «Следуй за мной».">Селфи-палка «Следуй<br> за мной»
Исправил

2022-11-07 13:58 UTC, merged