Добавляет второй заголовок
htmlacademy-htmlcss/2188619-device-35 pull request #3
Opened 2022-09-26 14:16 UTC by Aleksey177

2022-10-05 17:54 UTC, Aleksey177 reviewed
Добавляет разметку HTML

2022-10-06 10:41 UTC, Aleksey177 commented
Добавляет разметку HTML первой страницы

2022-10-09 16:27 UTC, Kartaviy-arteom requested changes

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +        </a>
ссылку саму на себя нет смысла давать, просто не указывай атрибут href

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +      <nav class="navigation-search">
тебе не обязательно оборачивать все ссылки в nav, можно ограничиться наиболее важными на твой взгляд. В nav могут быть так же не только ссылки

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +        </ul>
список тебе тут не нужен. Поиск это форма с инпутом ( к инпуту label) и кнопка.

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> + <!-- "навигация сайта" -->
каталог и плюс это кнопка для пока доп. меню. Img будет не нужен, плюс - декоративная графика
Каталог возможно так же сделать ссылкой, так как судя по макету каталога возможна страница "каталог" без выбранной категории

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +
список товаров, не находится внутри формы фильтров

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +  <h2 class="select-control-title">сортировка:</h2>
нет большого смысла в этом заголвке, если его и добавлять, то не h2

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +      <button class="sorting-button-up" type="submit">
внутри кнопки ссылок быть не должно, type=button

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +</main>
необходимо соблюдать структуру в отступов в документе, по всему документу

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +
Заголовок контакты будет внутри секции, <h2 class="visually-hidden">Логотип интернет магазина «Device»</h2> - не нужен

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +        <p class="footer-contacts-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
footer-contacts-address-text один лишний

2022-10-09 16:27 UTC, Kartaviy-arteom commented on catalog.html
> +    </li>
сначала нужно закрыть label

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +</header>
тут тоже самое что и на странице каталога

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +  </button>
кнопки смены слайдов, сами слайды представлены в стайлгайде

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +      </ul>
это будет список ссылок на страницы этих категорий

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +    <h2 class="services-text">Доставка</h2>
h2 здесь будет скрытый заголов обобщающие эти сервисы.

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +    <h3 class="services-text-delivery">Мы с удовольствием доставим ваш товар прямо к вашему подъезду совершенно бесплатно! Ведь мы неплохо заработаем, поднимая его на ваш этаж.</h3>
это не заголовок

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +    <img class="services-text-logo-delivery" src="" alt="Картинка Доставки">
эта картинка не нужна в размеке

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +    <a class="button button-all" href="#">Кредит</a>
ээто список с кнопками

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +</section>
это будет одна кнопка, показывающая модалку

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +    <a class="about-us-link"  href="#">Меловые линии</a>
детьми списка могут быть только li. Ссылки должны быть внутри li

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +    </li>
Элемент, который вложен в другой, должен иметь больший отступ

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +  <h3 class="contacts-title-site">Интернет-магазин «Девайс»</h3>
лучше выделить другим тегом

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +  <h4>пн—пт: с 10:00 до 22:00 <br>
это не заголовок

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +      <h2 class="mailing-title">Подпишитесь на рассылку</h2>
это не заголовок

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +            <span class="visually-hidden">Подписаться</span>
class="visually-hidden" здесь не нужен

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +  <input class="mailing-checkbox" type="checkbox" checked="yes">
это не input, у checked нет атрибута"yes"

2022-10-09 16:27 UTC, Kartaviy-arteom commented on index.html
> +  </footer>
теже комментарии что и на странице каталога

2022-10-10 12:15 UTC, Aleksey177 commented on catalog.html
> +        </a>
А как же при нажатии на лого попадать на главную страницу или только в index не делать, а в catalog нужно?

2022-10-10 13:13 UTC, Aleksey177 commented on catalog.html
> +      <nav class="navigation-search">
Заменил nav

2022-10-10 13:47 UTC, Aleksey177 commented on catalog.html
> +        </ul>
исправил

2022-10-10 14:15 UTC, Aleksey177 commented on catalog.html
> + <!-- "навигация сайта" -->
<h2 class="visually-hidden">Каталог товаров</h2>
          <a class="navigation-catalog" href="">Каталог товаров</a>
          <button class="navigation-catalog-button">
            </button>

написал так

2022-10-10 14:23 UTC, Aleksey177 commented on catalog.html
> +
убрал

2022-10-10 14:24 UTC, Aleksey177 commented on catalog.html
> +  <h2 class="select-control-title">сортировка:</h2>
убрал

2022-10-10 14:29 UTC, Aleksey177 commented on catalog.html
> +      <button class="sorting-button-up" type="submit">
исправил

2022-10-10 14:35 UTC, Aleksey177 commented on catalog.html
> +</main>
исправил

2022-10-10 14:37 UTC, Aleksey177 commented on catalog.html
> +
исправил

2022-10-10 14:38 UTC, Aleksey177 commented on catalog.html
> +        <p class="footer-contacts-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
убрал

2022-10-10 14:43 UTC, Aleksey177 commented on catalog.html
> +    </li>
исправил

2022-10-10 14:43 UTC, Aleksey177 commented on index.html
> +</header>
ок

2022-10-10 14:48 UTC, Aleksey177 commented on index.html
> +  </button>
Добавил класс для кнопок

2022-10-10 14:57 UTC, Aleksey177 commented on index.html
> +      </ul>
сделал ссылки

2022-10-10 15:01 UTC, Aleksey177 commented on index.html
> +    <h2 class="services-text">Доставка</h2>
ок

2022-10-10 15:10 UTC, Aleksey177 commented on index.html
> +    <h3 class="services-text-delivery">Мы с удовольствием доставим ваш товар прямо к вашему подъезду совершенно бесплатно! Ведь мы неплохо заработаем, поднимая его на ваш этаж.</h3>
исправил

2022-10-10 15:12 UTC, Aleksey177 commented on index.html
> +    <img class="services-text-logo-delivery" src="" alt="Картинка Доставки">
убрал

2022-10-10 15:26 UTC, Aleksey177 commented on index.html
> +    <a class="button button-all" href="#">Кредит</a>
исправил

2022-10-10 15:33 UTC, Aleksey177 commented on index.html
> +</section>
сделал одну кнопку

2022-10-10 15:35 UTC, Aleksey177 commented on index.html
> +    <a class="about-us-link"  href="#">Меловые линии</a>
не заметил лишние li

2022-10-10 15:36 UTC, Aleksey177 commented on index.html
> +    </li>
сделал

2022-10-10 15:48 UTC, Aleksey177 commented on index.html
> +  <h3 class="contacts-title-site">Интернет-магазин «Девайс»</h3>
ок

2022-10-10 15:48 UTC, Aleksey177 commented on index.html
> +  <h4>пн—пт: с 10:00 до 22:00 <br>
заменил на span

2022-10-10 15:49 UTC, Aleksey177 commented on index.html
> +      <h2 class="mailing-title">Подпишитесь на рассылку</h2>
заменил на span

2022-10-10 15:49 UTC, Aleksey177 commented on index.html
> +            <span class="visually-hidden">Подписаться</span>
убрал

2022-10-10 15:50 UTC, Aleksey177 commented on index.html
> +  <input class="mailing-checkbox" type="checkbox" checked="yes">
удалил

2022-10-10 15:50 UTC, Aleksey177 commented on index.html
> +  </footer>
ок

2022-10-12 19:19 UTC, Kartaviy-arteom requested changes

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> +        </label>
тут форма, с инпутом и кнопкой для оптправки. Ссылка внутри кнопки не должна быть

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> +            </button>
это кнопка не нужна

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> +</header>
необходимо соблюдать отступы, чтобы визульно было понятно вложенность и ее правильность

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> + <!--"товары с фильтром"-->
тут main открывается

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> +      <h3 class="catalog-products-title">фильтр:</h3>
заголовок лучше не внутри формы

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> +      </ul>
value у радиокнопок должен быть разный

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> +         <b class="product-card-price">500 ₽</b>
это тоже внутри ссылки

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> +      <ul class="product-list">
один список карточек, не несколько списков

2022-10-12 19:19 UTC, Kartaviy-arteom commented on catalog.html
> +  <section class="footer-navigation">
у секции должен быть заголовок

2022-10-12 19:19 UTC, Kartaviy-arteom commented on index.html
> +         <img class="catalog-devices-logo" src="" alt="Картинка Виртуальная реальность">
это декоративная графика в разметке здесь не нужна

2022-10-12 19:19 UTC, Kartaviy-arteom commented on index.html
> +
здесь будет список кнопок: доставка, гарантия, кредит. и обертка с 3 частями контента

2022-10-12 19:19 UTC, Kartaviy-arteom commented on index.html
> +</section>
отдельная секция для одной кнопки избыточно

2022-10-13 19:31 UTC, closed without merging