Подключает контентные изображения в разметке
htmlacademy-htmlcss/2188619-device-35 pull request #9
Opened 2022-10-14 17:46 UTC by Aleksey177

2022-10-15 09:17 UTC, Kartaviy-arteom requested changes
01, 02 в слайдере это текст, картинка не нужна
index-icon-delivery-rare-(!).svg - плохое имя для файла и тут нужна просо черная иконка без прозрачности.
там в названиях файлов нужно использовать англ слова, т.е ошибки в англ словах не пройдут критерий по наименованиям. Например (devvice).
Для стрелки сортировки, достаточно одной иконки, для второй можно в css развернуть первую

2022-10-15 09:17 UTC, Kartaviy-arteom commented on catalog.html
> -    </label>
форма

2022-10-15 09:17 UTC, Kartaviy-arteom commented on index.html
> +      </div>
форма

2022-10-15 09:17 UTC, Kartaviy-arteom commented on index.html
> +            <img class="catalog-devices-logo" src="" alt="Картинка Виртуальная реальность">
это лучше оставить декоративной графикой

2022-10-15 11:33 UTC, Aleksey177 commented on index.html
> +      </div>
Странно, у меня в vsc кнопка вынесена из label, запушу ещё раз посмотрим

2022-10-15 11:33 UTC, Aleksey177 commented on catalog.html
> -    </label>
Странно, у меня в vsc кнопка вынесена из label, запушу ещё раз посмотрим

2022-10-15 11:43 UTC, Aleksey177 commented on index.html
> +            <img class="catalog-devices-logo" src="" alt="Картинка Виртуальная реальность">
Убрал картинки

2022-10-16 14:21 UTC, Kartaviy-arteom approved these changes

2022-10-16 14:21 UTC, Kartaviy-arteom commented on catalog.html
> -    </label>
на главной исправлено, тут нет

2022-10-16 14:21 UTC, Kartaviy-arteom commented on catalog.html
> +                  <input class="control-input" type="radio" name="product-group" value="no">
пусть у одной из радиокнопок будет атрибут checked

2022-10-16 14:21 UTC, merged

2022-10-16 16:01 UTC, Aleksey177 commented on catalog.html
> +                  <input class="control-input" type="radio" name="product-group" value="no">
Сделал